[package]
name = "glean"
version = "0.0.1"
authors = [ "mordred@inaugust.com" ]

[dependencies]
rustc-serialize = "~0.3"
getopts = "~0.2"
glob = "*"
log = "*"

[lib]
name = "glean"
path = "src/lib.rs"

[[bin]]
name = "glean"
test = false
doc = false

[[test]]
name = "tests"
