[package]
name = "gleam"
version = "0.0.1"
authors = [ "mordred@inaugust.com" ]

[dependencies]
rustc-serialize = "~0.3"
getopts = "0.2.4"
glob = "*"

[lib]
name = "gleam"
path = "src/lib.rs"

[[bin]]
name = "gleam"
test = false
doc = false

[[test]]
name = "tests"
